export const products = [
  {
    id: 1,
    name: "Red Dress",
    category: "Dresses",
    price: 49.99,
    image: "/images/red-dress.jpg",
  },
  {
    id: 2,
    name: "Blue Dress",
    category: "Dresses",
    price: 39.99,
    image: "/images/blue-dress.jpg",
  },
  {
    id: 3,
    name: "Green Dress",
    category: "Dresses",
    price: 59.99,
    image: "/images/green-dress.jpg",
  },
  {
    id: 4,
    name: "Black Dress",
    category: "Dresses",
    price: 69.99,
    image: "/images/black-dress.jpg",
  },
  {
    id: 5,
    name: "White Dress",
    category: "Dresses",
    price: 29.99,
    image: "/images/white-dress.jpg",
  },
  {
    id: 6,
    name: "Leather Jacket",
    category: "Jackets",
    price: 89.99,
    image: "/images/leather-jacket.jpg",
  },
  {
    id: 7,
    name: "Denim Jacket",
    category: "Jackets",
    price: 79.99,
    image: "/images/denim-jacket.jpg",
  },
  {
    id: 8,
    name: "Winter Coat",
    category: "Coats",
    price: 129.99,
    image: "/images/winter-coat.jpg",
  },
  {
    id: 9,
    name: "Raincoat",
    category: "Coats",
    price: 89.99,
    image: "/images/raincoat.jpg",
  },
  {
    id: 10,
    name: "Beach Shorts",
    category: "Shorts",
    price: 24.99,
    image: "/images/beach-shorts.jpg",
  },
];
